### ISSUE TITLE
As a user I want to be able to update a Pet

### ISSUE THREAD

**Issue by ChrisRaynerSG** [GilbertR-Programmer/ApiTestingProject#2]

**Comment by ChrisRaynerSG** [comment]
2.1 @Sad
Given I send a PUT request to the API
When The Pet ID does Not exist
Then I should recieve a 404 pet not found status code

**Comment by ChrisRaynerSG** [comment]
2.2 @happy
Given I send a Put request to the API
When the pet ID is valid and is found
Then I should recieve a 200 status code
and the pet should be updated

**Comment by GilbertR-Programmer** [comment]
2.4 @Happy
Given I Have valid credentials
And I Submit a valid post request with new pet info
When I submit a gret request using that pet id
Then it should contain the udated information

**Comment by ChrisRaynerSG** [comment]
2.3 @sad
Given I send a PUT request to the API
When the Pet ID provided is not valid
Then I should receive a 400 status code

**Comment by ChrisRaynerSG** [comment]
2.5 @sad
Given I send a PUT request to the API
And I provide invalid information to be updated
When I send the request
Then I should recieve a 405 Validation Exception status code
